SUFFIX="requires a review and whitelisting by the SUSE security team"

cron-file-unauthorized="Packaging cron jobs #SUFFIX#. #REVIEW_NEEDED_TEXT#"
cron-file-digest-mismatch="A whitelisted cron job related file changed in content. Packaging cron jobs #SUFFIX#. #REVIEW_NEEDED_TEXT#"
cron-file-ghost="This package installs a cron job as a %ghost file. #GHOST_ENCOUNTERED_TEXT#"
# we allow symlinks for cron jobs, we just add this to satisfy unit tests
cron-file-symlink="this should never happen"

# The binary PAM modules are whitelisted without digests so -mismatch should
# not occur here
pam-file-unauthorized="Packaging new PAM modules #SUFFIX#. #REVIEW_NEEDED_TEXT#"
pam-file-ghost="This package installs a PAM module as a %ghost file. #GHOST_ENCOUNTERED_TEXT#"
pam-file-symlink="this should never happen"

permissions-file-unauthorized="Packaging permissions.d drop-in snippets #SUFFIX#. #REVIEW_NEEDED_TEXT#"
permissions-file-digest-mismatch="A permissions.d drop-in snippet changed in content. Packaging permissions.d drop-in snippets #SUFFIX#. #REVIEW_NEEDED_TEXT#"
permissions-file-ghost="This package installs a permissions drop-in file as a %ghost file. #GHOST_ENCOUNTERED_TEXT#"
permissions-file-symlink="Symlinks are not allowed for permissions.d drop-in snippets"

polkit-file-unauthorized="Packaging polkit rules #SUFFIX#. #REVIEW_NEEDED_TEXT#"
polkit-file-digest-mismatch="A polkit rule file changed in content. Packaging polkit rules #SUFFIX#. #REVIEW_NEEDED_TEXT#"
polkit-file-ghost="This package installs a polkit rule file as a %ghost file. #GHOST_ENCOUNTERED_TEXT#"
polkit-file-symlink="Symlinks are not allowed for polkit rule files"

dbus-file-unauthorized="Packaging D-Bus services #SUFFIX#. #REVIEW_NEEDED_TEXT#"
dbus-file-digest-mismatch="A D-Bus configuration file changed in content. Packaging D-Bus services #SUFFIX#. #REVIEW_NEEDED_TEXT#"
dbus-file-ghost="This package installs a D-Bus configuration file as a %ghost file. #GHOST_ENCOUNTERED_TEXT#"
dbus-file-symlink="Symlinks are not allowed for D-Bus configuration files"
dbus-file-parse-error="A digest of an D-Bus XML file could not be computed, because of an XML parsing error"
