[[FileDigestGroup]]
package = "rpmlint-integration-test"
type = "cron"
note = "valid test whitelisting entry for the OBS integration test package"
bug = "bsc#1188704"
[[FileDigestGroup.digests]]
path = "/etc/cron.hourly/rpmlint_cron"
hash = "3cf3c05e5c37b0ee7b793f9c5c9b57b74071b02137a7e66a10a52d91e0ddbc51"

[[FileDigestGroup]]
package = "rpmlint-integration-test"
type = "cron"
note = "mismatching test whitelisting entry for the OBS integration test package"
bug = "bsc#1188704"
[[FileDigestGroup.digests]]
path = "/etc/cron.hourly/rpmlint_mismatch"
hash = "4a5e8e9ca514c73f1dbee55e88c4d75a235473c1d5cef4751d84016833961fdf"

[[FileDigestGroup]]
package = "cronie-anacron"
type = "cron"
note = "Executes daily, weekly, monthly cron jobs"
bugs = ["bsc#1150541", "bsc#1190521", "bsc#1218107", "bsc#1218756"]
[[FileDigestGroup.digests]]
path = "/etc/cron.hourly/0anacron"
digester = "shell"
hash = "6981b346a1cdafbc018c6f69819a28994c64d9b0a9d6365235f1a79b7054312f"

[[FileDigestGroup]]
package = "patch2mail"
type = "cron"
note = "looks up pending zypper patches and sens them out by mail"
bug = "bsc#1150552"
[[FileDigestGroup.digests]]
path = "/etc/cron.daily/patch2mail"
hash = "2db3aaa7addba83e60e24fdb868dd6f353bfb76b005fd2a2fdaf079fb54fe597"

[[FileDigestGroup]]
package = "nextcloud"
type = "cron"
note = "default-disabled cron job that runs PHP cleanup logic for nextcloud as unprivileged user"
bug = "bsc#1162254"
[[FileDigestGroup.digests]]
path = "/etc/cron.d/nextcloud"
hash = "176aed8f9adc79cc3d0a75a223730d621cf9435d7baee03823afc558c110b76d"

[[FileDigestGroup]]
package = "nextcloud"
type = "cron"
note = "follow-up whitelisting for no-op change in comments"
bug = "bsc#1168964"
[[FileDigestGroup.digests]]
path = "/etc/cron.d/nextcloud"
hash = "5f883ad50e790de95f4ffbafd9515dc0bc88f9e49fcb404d16ed0d781fbd4c77"

[[FileDigestGroup]]
package = "matomo"
type = "cron"
note = "a complex PHP script is called as wwwrun user"
bug = "bsc#1150548"
[[FileDigestGroup.digests]]
path = "/etc/cron.d/matomo-archive"
hash = "b55bb543d9e890522aaabd016e8e8c80e3d0b6529f10da3ea264348e375eaf82"

[[FileDigestGroup]]
package = "ppc64-diag"
type = "cron"
note = "ppc specific hardware health diagnosis and error reporting"
bug = "bsc#1172859"
[[FileDigestGroup.digests]]
path = "/etc/cron.daily/run_diag_encl"
hash = "5519586bca9edc47be4c76faa7353eb8a0ecd68b9f04c0b20e7acfdb9d9eb261"

