# Whitelistings for device files

[[DeviceFilesWhitelist]]
package = "rpmlint-integration-test"
bug = "bsc#1188704"
note = "test whitelisting entry for the OBS integration test package"
files = [
  {
    path = '/mydev/mychr',
    mode = "crw-rw-rw-",
    owner = "root",
    group = "root",
    device_minor = 3,
    device_major = 1
  },
  {
    path = '/mydev/myblk',
    mode = "brw-rw-rw-",
    owner = "root",
    group = "root",
    device_minor = 8,
    device_major = 1
  },
  {
    path = '/mydev/myblk2',
    mode = "brw-rw----",
    owner = "root",
    group = "root",
    device_minor = 9,
    device_major = 1
  }
]
