[[FileDigestGroup]]
package = "rpmlint-integration-test"
note = "valid test whitelisting entry for the OBS integration test package"
type = "permissions"
digests = [
    {
        path = "/etc/permissions.d/valid",
        algorithm = "sha256",
        hash = "3c07438f28b0545bfe83a2355693c94b91e3fe380c07f12d542e9d27a08de1f9"
    },
]

[[FileDigestGroup]]
package = "rpmlint-integration-test"
note = "mismatching test whitelisting entry for the OBS integration test package"
type = "permissions"
digests = [
    {
        path = "/etc/permissions.d/mismatch",
        algorithm = "sha256",
        hash = "4a5e8e9ca514c73f1dbee55e88c4d75a235473c1d5cef4751d84016833961fdf"
    },
]

[[FileDigestGroup]]
package = "postfix"
type = "permissions"
digests = [
    {
        path = "/etc/permissions.d/postfix",
        algorithm = "sha256",
        hash = "6233f37dc93ae05d476bbeb03ffa6de4d006893a9d5c91d38afb66506d224e9d"
    },
    {
        path = "/etc/permissions.d/postfix.paranoid",
        algorithm = "sha256",
        hash = "d5e51380e7ec868a42d336c868fc012ab95cac771d95361504cc6040b8d86221"
    },
]

[[FileDigestGroup]]
package = "sendmail"
type = "permissions"
digests = [
    {
        path = "/etc/permissions.d/sendmail",
        algorithm = "sha256",
        hash = "8dded55101e7040cf912936d62198202aa4354a2da457352f64f513f10ed6b92"
    },
    {
        path = "/etc/permissions.d/sendmail.paranoid",
        algorithm = "sha256",
        hash = "bf4067f280e6d85b1b081ccfb7492d61505225f8ecfa3c3cc02ecf4ec0b298c1"
    },
]

[[FileDigestGroup]]
package = "texlive-filesystem"
type = "permissions"
digests = [
    {
        path = "/etc/permissions.d/texlive",
        algorithm = "sha256",
        hash = "9b4b799427c31ec0be73b6b363d2d1aea8d51e22db6f207dd0660f6a1423a5ee"
    },
    {
        path = "/etc/permissions.d/texlive.texlive",
        algorithm = "sha256",
        hash = "9b4b799427c31ec0be73b6b363d2d1aea8d51e22db6f207dd0660f6a1423a5ee"
    },
]
