# Configuration for security checks

[FileDigestLocation.cron]
FollowSymlinks = true
Locations = [
    "/etc/cron.d/",
    "/etc/cron.hourly/",
    "/etc/cron.daily/",
    "/etc/cron.weekly/",
    "/etc/cron.monthly/"
]

[FileDigestLocation.dbus]
FollowSymlinks = false
Locations = [
    "/usr/share/dbus-1/system-services/",
    "/usr/share/dbus-1/system.d/",
    "/etc/dbus-1/system.d/"
]

[FileDigestLocation.polkit]
FollowSymlinks = false
Locations = [
    "/etc/polkit-default-privs.d/",
    "/etc/polkit-1/rules.d/",
    "/usr/share/polkit-1/rules.d/"
]

[FileDigestLocation.permissions]
FollowSymlinks = false
Locations = [
    "/etc/permissions.d/",
    "/usr/share/permissions/permissions.d/"
]

[FileDigestLocation.pam]
# a single PAM module uses a symlink: pam_krb5afs.so from pam_krb5
# so we need to accept symlinks here
FollowSymlinks = true
NamePatterns = [
    "*.so",
]
Locations = [
    "/usr/lib/security/",
    "/usr/lib64/security/",
    "/lib/security/",
    "/lib64/security/"
]
